"""tables update

Revision ID: 0157afb9a9cb
Revises: c1a818822b43
Create Date: 2020-07-23 22:35:37.981337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0157afb9a9cb'
down_revision = 'c1a818822b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_city'), ['city'], unique=False)
        batch_op.drop_index('ix_post_City')
        batch_op.drop_column('City')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('City', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index('ix_post_City', ['City'], unique=False)
        batch_op.drop_index(batch_op.f('ix_post_city'))
        batch_op.drop_column('city')

    # ### end Alembic commands ###
