"""update table1

Revision ID: 0de082680838
Revises: 2656778f931f
Create Date: 2020-07-14 23:41:18.990660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de082680838'
down_revision = '2656778f931f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postCategory_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('softwareCategory_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_category_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_category_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_category_softwareCategory_id_software'), 'software', ['softwareCategory_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_category_postCategory_id_post'), 'post', ['postCategory_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postComment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('softwareComment_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_comment_post_id_post', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_postComment_id_post'), 'post', ['postComment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_softwareComment_id_software'), 'software', ['softwareComment_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postReport_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('softwareReport_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_report_post_id_post', type_='foreignkey')
        batch_op.drop_constraint('fk_report_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_report_softwareReport_id_software'), 'software', ['softwareReport_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_report_postReport_id_post'), 'post', ['postReport_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postSimilar_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('softwarSimilare_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_similar_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_similar_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_similar_softwarSimilare_id_software'), 'software', ['softwarSimilare_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_similar_postSimilar_id_post'), 'post', ['postSimilar_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postTag_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('softwareTag_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_tag_post_id_post', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tag_postTag_id_post'), 'post', ['postTag_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_softwareTag_id_software'), 'software', ['softwareTag_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tag_softwareTag_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_postTag_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tag_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_tag_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.drop_column('softwareTag_id')
        batch_op.drop_column('postTag_id')

    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_similar_postSimilar_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_similar_softwarSimilare_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_similar_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_similar_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.drop_column('softwarSimilare_id')
        batch_op.drop_column('postSimilar_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_report_postReport_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_report_softwareReport_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_report_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_report_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.drop_column('softwareReport_id')
        batch_op.drop_column('postReport_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comment_softwareComment_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_postComment_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.drop_column('softwareComment_id')
        batch_op.drop_column('postComment_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_category_postCategory_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_category_softwareCategory_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_category_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_category_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.drop_column('softwareCategory_id')
        batch_op.drop_column('postCategory_id')

    # ### end Alembic commands ###
