"""add Menssage

Revision ID: 247eaf5a09f0
Revises: 4d753390905a
Create Date: 2020-08-21 20:49:37.753940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247eaf5a09f0'
down_revision = '4d753390905a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_message_recipient_id_user')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_message_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    # ### end Alembic commands ###
