"""tag N pra N

Revision ID: 254beea8eec1
Revises: b91516ab5705
Create Date: 2020-10-07 19:46:00.200173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254beea8eec1'
down_revision = 'b91516ab5705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('fk_Tags_software_id_software')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_Tags_source_id_source')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_Tags_tag_id_tag')),
    sa.PrimaryKeyConstraint('tag_id', 'source_id', 'software_id', name=op.f('pk_Tags'))
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('software_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name='fk_tags_software_id_software'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_tags_source_id_source'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='fk_tags_tag_id_tag'),
    sa.PrimaryKeyConstraint('tag_id', 'source_id', 'software_id', name='pk_tags')
    )
    op.drop_table('Tags')
    # ### end Alembic commands ###
