"""Models

Revision ID: 2896e96563e8
Revises: ef9b98b18a9a
Create Date: 2019-10-20 21:12:06.006010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2896e96563e8'
down_revision = 'ef9b98b18a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_data'), 'comentario', ['data'], unique=False)
    op.create_index(op.f('ix_comentario_texto'), 'comentario', ['texto'], unique=False)
    op.create_table('denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denuncia_descricao'), 'denuncia', ['descricao'], unique=False)
    op.create_index(op.f('ix_denuncia_tipo'), 'denuncia', ['tipo'], unique=False)
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gostei', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorito_gostei'), 'favorito', ['gostei'], unique=False)
    op.create_table('fonte_dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=70), nullable=True),
    sa.Column('esfera', sa.String(length=110), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('linkOficial', sa.String(length=200), nullable=True),
    sa.Column('linkDataset', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fonte_dados_descricao'), 'fonte_dados', ['descricao'], unique=False)
    op.create_index(op.f('ix_fonte_dados_esfera'), 'fonte_dados', ['esfera'], unique=False)
    op.create_index(op.f('ix_fonte_dados_linkDataset'), 'fonte_dados', ['linkDataset'], unique=False)
    op.create_index(op.f('ix_fonte_dados_linkOficial'), 'fonte_dados', ['linkOficial'], unique=False)
    op.create_index(op.f('ix_fonte_dados_titulo'), 'fonte_dados', ['titulo'], unique=False)
    op.create_table('software_dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=70), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('dataCriacao', sa.String(length=10), nullable=True),
    sa.Column('dataLancamento', sa.String(length=10), nullable=True),
    sa.Column('linkDownload', sa.String(length=200), nullable=True),
    sa.Column('desenvolvimentoAtivo', sa.String(length=200), nullable=True),
    sa.Column('licenca', sa.String(length=10), nullable=True),
    sa.Column('proprietario', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_dados_dataCriacao'), 'software_dados', ['dataCriacao'], unique=False)
    op.create_index(op.f('ix_software_dados_dataLancamento'), 'software_dados', ['dataLancamento'], unique=False)
    op.create_index(op.f('ix_software_dados_descricao'), 'software_dados', ['descricao'], unique=False)
    op.create_index(op.f('ix_software_dados_desenvolvimentoAtivo'), 'software_dados', ['desenvolvimentoAtivo'], unique=False)
    op.create_index(op.f('ix_software_dados_licenca'), 'software_dados', ['licenca'], unique=False)
    op.create_index(op.f('ix_software_dados_linkDownload'), 'software_dados', ['linkDownload'], unique=False)
    op.create_index(op.f('ix_software_dados_proprietario'), 'software_dados', ['proprietario'], unique=False)
    op.create_index(op.f('ix_software_dados_titulo'), 'software_dados', ['titulo'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palavraChave', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_palavraChave'), 'tag', ['palavraChave'], unique=False)
    op.create_table('tipo_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_usuario_nome'), 'tipo_usuario', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_usuario_nome'), table_name='tipo_usuario')
    op.drop_table('tipo_usuario')
    op.drop_index(op.f('ix_tag_palavraChave'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_software_dados_titulo'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_proprietario'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_linkDownload'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_licenca'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_desenvolvimentoAtivo'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_descricao'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_dataLancamento'), table_name='software_dados')
    op.drop_index(op.f('ix_software_dados_dataCriacao'), table_name='software_dados')
    op.drop_table('software_dados')
    op.drop_index(op.f('ix_fonte_dados_titulo'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_linkOficial'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_linkDataset'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_esfera'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_descricao'), table_name='fonte_dados')
    op.drop_table('fonte_dados')
    op.drop_index(op.f('ix_favorito_gostei'), table_name='favorito')
    op.drop_table('favorito')
    op.drop_index(op.f('ix_denuncia_tipo'), table_name='denuncia')
    op.drop_index(op.f('ix_denuncia_descricao'), table_name='denuncia')
    op.drop_table('denuncia')
    op.drop_index(op.f('ix_comentario_texto'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_data'), table_name='comentario')
    op.drop_table('comentario')
    # ### end Alembic commands ###
