"""update tabelas

Revision ID: 2a981d0ffda1
Revises: 31aea7bc50e7
Create Date: 2020-03-24 20:25:38.519300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a981d0ffda1'
down_revision = '31aea7bc50e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_data'), 'comentario', ['data'], unique=False)
    op.create_index(op.f('ix_comentario_texto'), 'comentario', ['texto'], unique=False)
    op.create_table('denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denuncia_descricao'), 'denuncia', ['descricao'], unique=False)
    op.create_index(op.f('ix_denuncia_tipo'), 'denuncia', ['tipo'], unique=False)
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gostei', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorito_gostei'), 'favorito', ['gostei'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palavraChave', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_palavraChave'), 'tag', ['palavraChave'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('about_me', sa.String(length=300), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_categorie'), 'post', ['categorie'], unique=False)
    op.create_index(op.f('ix_post_description'), 'post', ['description'], unique=False)
    op.create_index(op.f('ix_post_officialLink'), 'post', ['officialLink'], unique=False)
    op.create_index(op.f('ix_post_sphere'), 'post', ['sphere'], unique=False)
    op.create_index(op.f('ix_post_tag'), 'post', ['tag'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=True)
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=800), nullable=True),
    sa.Column('categorie', sa.String(length=800), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('downloadLink', sa.String(length=300), nullable=True),
    sa.Column('activeDevelopment', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('dateCreation', sa.String(length=300), nullable=True),
    sa.Column('dateRelease', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_activeDevelopment'), 'software', ['activeDevelopment'], unique=False)
    op.create_index(op.f('ix_software_categorie'), 'software', ['categorie'], unique=False)
    op.create_index(op.f('ix_software_dateCreation'), 'software', ['dateCreation'], unique=False)
    op.create_index(op.f('ix_software_dateRelease'), 'software', ['dateRelease'], unique=False)
    op.create_index(op.f('ix_software_description'), 'software', ['description'], unique=False)
    op.create_index(op.f('ix_software_downloadLink'), 'software', ['downloadLink'], unique=False)
    op.create_index(op.f('ix_software_license'), 'software', ['license'], unique=False)
    op.create_index(op.f('ix_software_owner'), 'software', ['owner'], unique=False)
    op.create_index(op.f('ix_software_tag'), 'software', ['tag'], unique=False)
    op.create_index(op.f('ix_software_timestamp'), 'software', ['timestamp'], unique=False)
    op.create_index(op.f('ix_software_title'), 'software', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_title'), table_name='software')
    op.drop_index(op.f('ix_software_timestamp'), table_name='software')
    op.drop_index(op.f('ix_software_tag'), table_name='software')
    op.drop_index(op.f('ix_software_owner'), table_name='software')
    op.drop_index(op.f('ix_software_license'), table_name='software')
    op.drop_index(op.f('ix_software_downloadLink'), table_name='software')
    op.drop_index(op.f('ix_software_description'), table_name='software')
    op.drop_index(op.f('ix_software_dateRelease'), table_name='software')
    op.drop_index(op.f('ix_software_dateCreation'), table_name='software')
    op.drop_index(op.f('ix_software_categorie'), table_name='software')
    op.drop_index(op.f('ix_software_activeDevelopment'), table_name='software')
    op.drop_table('software')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_tag'), table_name='post')
    op.drop_index(op.f('ix_post_sphere'), table_name='post')
    op.drop_index(op.f('ix_post_officialLink'), table_name='post')
    op.drop_index(op.f('ix_post_description'), table_name='post')
    op.drop_index(op.f('ix_post_categorie'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_palavraChave'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_favorito_gostei'), table_name='favorito')
    op.drop_table('favorito')
    op.drop_index(op.f('ix_denuncia_tipo'), table_name='denuncia')
    op.drop_index(op.f('ix_denuncia_descricao'), table_name='denuncia')
    op.drop_table('denuncia')
    op.drop_index(op.f('ix_comentario_texto'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_data'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
