"""update

Revision ID: 2c821c23acd7
Revises: bdceaac98067
Create Date: 2020-08-22 00:50:31.105734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c821c23acd7'
down_revision = 'bdceaac98067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_category_software_category_id_software'), 'software', ['software_category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_category_source_category_id_source'), 'source', ['source_category_id'], ['id'])

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_constraint('fk_software_tag_id_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_software_category_id_category', type_='foreignkey')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint('fk_source_tag_id_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_source_category_id_category', type_='foreignkey')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_tag_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tag_source_tag_id_source'), 'source', ['source_tag_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_software_tag_id_software'), 'software', ['software_tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tag_software_tag_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_source_tag_id_source'), type_='foreignkey')
        batch_op.drop_column('source_tag_id')
        batch_op.drop_column('software_tag_id')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_source_category_id_category', 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_source_tag_id_tag', 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_software_category_id_category', 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_software_tag_id_tag', 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_source_category_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_category_software_category_id_software'), type_='foreignkey')
        batch_op.drop_column('source_category_id')
        batch_op.drop_column('software_category_id')

    # ### end Alembic commands ###
