"""relacionamento comment text

Revision ID: 2f190bc30eb5
Revises: bbac38b29ee9
Create Date: 2020-03-27 15:28:51.943744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f190bc30eb5'
down_revision = 'bbac38b29ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('text', sa.String(length=600), nullable=True))
    op.create_index(op.f('ix_comment_text'), 'comment', ['text'], unique=False)
    op.drop_index('ix_comment_comment', table_name='comment')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.VARCHAR(length=600), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_index('ix_comment_comment', 'comment', ['comment'], unique=False)
    op.drop_index(op.f('ix_comment_text'), table_name='comment')
    op.drop_column('comment', 'text')
    # ### end Alembic commands ###
