"""update tabelas

Revision ID: 2fbcccd86f86
Revises: caaf1f9ec27e
Create Date: 2020-03-24 20:20:48.795113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbcccd86f86'
down_revision = 'caaf1f9ec27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('about_me', sa.String(length=300), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_categorie'), 'post', ['categorie'], unique=False)
    op.create_index(op.f('ix_post_description'), 'post', ['description'], unique=False)
    op.create_index(op.f('ix_post_officialLink'), 'post', ['officialLink'], unique=False)
    op.create_index(op.f('ix_post_sphere'), 'post', ['sphere'], unique=False)
    op.create_index(op.f('ix_post_tag'), 'post', ['tag'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=True)
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=800), nullable=True),
    sa.Column('categorie', sa.String(length=800), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('downloadLink', sa.String(length=300), nullable=True),
    sa.Column('activeDevelopment', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('dateCreation', sa.String(length=300), nullable=True),
    sa.Column('dateRelease', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_activeDevelopment'), 'software', ['activeDevelopment'], unique=False)
    op.create_index(op.f('ix_software_categorie'), 'software', ['categorie'], unique=False)
    op.create_index(op.f('ix_software_dateCreation'), 'software', ['dateCreation'], unique=False)
    op.create_index(op.f('ix_software_dateRelease'), 'software', ['dateRelease'], unique=False)
    op.create_index(op.f('ix_software_description'), 'software', ['description'], unique=False)
    op.create_index(op.f('ix_software_downloadLink'), 'software', ['downloadLink'], unique=False)
    op.create_index(op.f('ix_software_license'), 'software', ['license'], unique=False)
    op.create_index(op.f('ix_software_owner'), 'software', ['owner'], unique=False)
    op.create_index(op.f('ix_software_tag'), 'software', ['tag'], unique=False)
    op.create_index(op.f('ix_software_timestamp'), 'software', ['timestamp'], unique=False)
    op.create_index(op.f('ix_software_title'), 'software', ['title'], unique=True)
    op.drop_index('ix_softwares_activeDevelopment', table_name='softwares')
    op.drop_index('ix_softwares_categorie', table_name='softwares')
    op.drop_index('ix_softwares_dateCreation', table_name='softwares')
    op.drop_index('ix_softwares_dateRelease', table_name='softwares')
    op.drop_index('ix_softwares_description', table_name='softwares')
    op.drop_index('ix_softwares_downloadLink', table_name='softwares')
    op.drop_index('ix_softwares_license', table_name='softwares')
    op.drop_index('ix_softwares_owner', table_name='softwares')
    op.drop_index('ix_softwares_tag', table_name='softwares')
    op.drop_index('ix_softwares_timestamp', table_name='softwares')
    op.drop_index('ix_softwares_title', table_name='softwares')
    op.drop_table('softwares')
    op.drop_index('ix_posts_categorie', table_name='posts')
    op.drop_index('ix_posts_description', table_name='posts')
    op.drop_index('ix_posts_officialLink', table_name='posts')
    op.drop_index('ix_posts_sphere', table_name='posts')
    op.drop_index('ix_posts_tag', table_name='posts')
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_index('ix_posts_title', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=150), nullable=True),
    sa.Column('about_me', sa.VARCHAR(length=300), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sphere', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), nullable=True),
    sa.Column('officialLink', sa.VARCHAR(length=300), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=True),
    sa.Column('categorie', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_title', 'posts', ['title'], unique=1)
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    op.create_index('ix_posts_tag', 'posts', ['tag'], unique=False)
    op.create_index('ix_posts_sphere', 'posts', ['sphere'], unique=False)
    op.create_index('ix_posts_officialLink', 'posts', ['officialLink'], unique=False)
    op.create_index('ix_posts_description', 'posts', ['description'], unique=False)
    op.create_index('ix_posts_categorie', 'posts', ['categorie'], unique=False)
    op.create_table('softwares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), nullable=True),
    sa.Column('downloadLink', sa.VARCHAR(length=300), nullable=True),
    sa.Column('activeDevelopment', sa.VARCHAR(length=200), nullable=True),
    sa.Column('license', sa.VARCHAR(length=200), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dateCreation', sa.VARCHAR(length=300), nullable=True),
    sa.Column('dateRelease', sa.VARCHAR(length=300), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('categorie', sa.VARCHAR(length=800), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=800), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_softwares_title', 'softwares', ['title'], unique=1)
    op.create_index('ix_softwares_timestamp', 'softwares', ['timestamp'], unique=False)
    op.create_index('ix_softwares_tag', 'softwares', ['tag'], unique=False)
    op.create_index('ix_softwares_owner', 'softwares', ['owner'], unique=False)
    op.create_index('ix_softwares_license', 'softwares', ['license'], unique=False)
    op.create_index('ix_softwares_downloadLink', 'softwares', ['downloadLink'], unique=False)
    op.create_index('ix_softwares_description', 'softwares', ['description'], unique=False)
    op.create_index('ix_softwares_dateRelease', 'softwares', ['dateRelease'], unique=False)
    op.create_index('ix_softwares_dateCreation', 'softwares', ['dateCreation'], unique=False)
    op.create_index('ix_softwares_categorie', 'softwares', ['categorie'], unique=False)
    op.create_index('ix_softwares_activeDevelopment', 'softwares', ['activeDevelopment'], unique=False)
    op.drop_index(op.f('ix_software_title'), table_name='software')
    op.drop_index(op.f('ix_software_timestamp'), table_name='software')
    op.drop_index(op.f('ix_software_tag'), table_name='software')
    op.drop_index(op.f('ix_software_owner'), table_name='software')
    op.drop_index(op.f('ix_software_license'), table_name='software')
    op.drop_index(op.f('ix_software_downloadLink'), table_name='software')
    op.drop_index(op.f('ix_software_description'), table_name='software')
    op.drop_index(op.f('ix_software_dateRelease'), table_name='software')
    op.drop_index(op.f('ix_software_dateCreation'), table_name='software')
    op.drop_index(op.f('ix_software_categorie'), table_name='software')
    op.drop_index(op.f('ix_software_activeDevelopment'), table_name='software')
    op.drop_table('software')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_tag'), table_name='post')
    op.drop_index(op.f('ix_post_sphere'), table_name='post')
    op.drop_index(op.f('ix_post_officialLink'), table_name='post')
    op.drop_index(op.f('ix_post_description'), table_name='post')
    op.drop_index(op.f('ix_post_categorie'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
