"""update tables

Revision ID: 30f6c46a8de4
Revises: fea1e2d059a4
Create Date: 2020-07-14 22:05:44.121278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f6c46a8de4'
down_revision = 'fea1e2d059a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_category_post_id_post')),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('fk_category_software_id_software')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_timestamp'), ['timestamp'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_report_post_id_post')),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('fk_report_software_id_software')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_type'), ['type'], unique=False)

    op.drop_table('categoria')
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.drop_index('ix_denuncia_descricao')
        batch_op.drop_index('ix_denuncia_tipo')

    op.drop_table('denuncia')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_software_id_software'), 'software', ['software_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_categorie')
        batch_op.drop_index('ix_post_tag')
        batch_op.drop_column('tag')
        batch_op.drop_column('categorie')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_index('ix_software_categorie')
        batch_op.drop_index('ix_software_tag')
        batch_op.drop_column('tag')
        batch_op.drop_column('categorie')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tag_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_index('ix_tag_palavraChave')
        batch_op.create_foreign_key(batch_op.f('fk_tag_software_id_software'), 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_post_id_post'), 'post', ['post_id'], ['id'])
        batch_op.drop_column('palavraChave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('palavraChave', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tag_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_software_id_software'), type_='foreignkey')
        batch_op.create_index('ix_tag_palavraChave', ['palavraChave'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tag_timestamp'))
        batch_op.drop_index(batch_op.f('ix_tag_tag'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('tag')
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.VARCHAR(length=800), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=800), nullable=True))
        batch_op.create_index('ix_software_tag', ['tag'], unique=False)
        batch_op.create_index('ix_software_categorie', ['categorie'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index('ix_post_tag', ['tag'], unique=False)
        batch_op.create_index('ix_post_categorie', ['categorie'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_software_id_software'), type_='foreignkey')
        batch_op.drop_column('software_id')

    op.create_table('denuncia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=500), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('denuncia', schema=None) as batch_op:
        batch_op.create_index('ix_denuncia_tipo', ['tipo'], unique=False)
        batch_op.create_index('ix_denuncia_descricao', ['descricao'], unique=False)

    op.create_table('categoria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_type'))
        batch_op.drop_index(batch_op.f('ix_report_timestamp'))
        batch_op.drop_index(batch_op.f('ix_report_name'))
        batch_op.drop_index(batch_op.f('ix_report_description'))

    op.drop_table('report')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_timestamp'))
        batch_op.drop_index(batch_op.f('ix_category_category'))

    op.drop_table('category')
    # ### end Alembic commands ###
