"""add autocomplete

Revision ID: 32282709bb58
Revises: afb3556458da
Create Date: 2020-07-02 02:24:01.884020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32282709bb58'
down_revision = 'afb3556458da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.VARCHAR(length=600), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
