"""bd softwares timestamp

Revision ID: 3251458bf6f0
Revises: 4ae782f1bed5
Create Date: 2020-03-23 21:47:46.412140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3251458bf6f0'
down_revision = '4ae782f1bed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_softwares_timestamp'), 'softwares', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_softwares_timestamp'), table_name='softwares')
    op.drop_column('softwares', 'timestamp')
    # ### end Alembic commands ###
