"""usuario remove typeUser

Revision ID: 390a0aa7f540
Revises: 5e68ccd9be04
Create Date: 2020-03-19 20:10:07.079387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390a0aa7f540'
down_revision = '5e68ccd9be04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'typeUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('typeUser', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
