"""update

Revision ID: 3f8d4febc7b9
Revises: f73dca375992
Create Date: 2020-08-22 18:00:20.691995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8d4febc7b9'
down_revision = 'f73dca375992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.drop_index('ix_similar_name')
        batch_op.drop_index('ix_similar_timestamp')

    op.drop_table('similar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.Column('software_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name='fk_similar_software_id_software'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_similar_source_id_source'),
    sa.PrimaryKeyConstraint('id', name='pk_similar')
    )
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.create_index('ix_similar_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_similar_name', ['name'], unique=False)

    # ### end Alembic commands ###
