"""update

Revision ID: 42fa74eecc54
Revises: c9d74deeb2ce
Create Date: 2020-09-21 19:12:32.329223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fa74eecc54'
down_revision = 'c9d74deeb2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_source_id_source'), 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_software_id_software'), 'software', ['software_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_source_id_source'), type_='foreignkey')
        batch_op.drop_column('source_id')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###
