"""add similar

Revision ID: 43e51f930d79
Revises: d0f662810095
Create Date: 2020-07-08 22:44:02.966625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e51f930d79'
down_revision = 'd0f662810095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'comment')
    op.add_column('similar', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_index('ix_similar_name', table_name='similar')
    op.create_index(op.f('ix_similar_name'), 'similar', ['name'], unique=False)
    op.create_foreign_key(None, 'similar', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'similar', type_='foreignkey')
    op.drop_index(op.f('ix_similar_name'), table_name='similar')
    op.create_index('ix_similar_name', 'similar', ['name'], unique=1)
    op.drop_column('similar', 'post_id')
    op.add_column('comment', sa.Column('comment', sa.VARCHAR(length=600), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
