"""table user e source

Revision ID: 49938ad6c2d9
Revises: cabdb28e0cdc
Create Date: 2019-11-09 23:50:49.093053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49938ad6c2d9'
down_revision = 'cabdb28e0cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
