"""criei tabelas

Revision ID: 4ae782f1bed5
Revises: 23921936f8ef
Create Date: 2020-03-22 01:10:18.483167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae782f1bed5'
down_revision = '23921936f8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('about_me', sa.String(length=300), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_description'), 'posts', ['description'], unique=False)
    op.create_index(op.f('ix_posts_officialLink'), 'posts', ['officialLink'], unique=False)
    op.create_index(op.f('ix_posts_sphere'), 'posts', ['sphere'], unique=False)
    op.create_index(op.f('ix_posts_tag'), 'posts', ['tag'], unique=True)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=True)
    op.create_table('softwares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('downloadLink', sa.String(length=300), nullable=True),
    sa.Column('activeDevelopment', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('dateCreation', sa.String(length=300), nullable=True),
    sa.Column('dateRelease', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_softwares_activeDevelopment'), 'softwares', ['activeDevelopment'], unique=False)
    op.create_index(op.f('ix_softwares_dateCreation'), 'softwares', ['dateCreation'], unique=False)
    op.create_index(op.f('ix_softwares_dateRelease'), 'softwares', ['dateRelease'], unique=False)
    op.create_index(op.f('ix_softwares_description'), 'softwares', ['description'], unique=False)
    op.create_index(op.f('ix_softwares_downloadLink'), 'softwares', ['downloadLink'], unique=False)
    op.create_index(op.f('ix_softwares_license'), 'softwares', ['license'], unique=False)
    op.create_index(op.f('ix_softwares_owner'), 'softwares', ['owner'], unique=False)
    op.create_index(op.f('ix_softwares_title'), 'softwares', ['title'], unique=True)
    op.drop_index('ix_fonte_dados_descricao', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_esfera', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_linkDataset', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_linkOficial', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_titulo', table_name='fonte_dados')
    op.drop_table('fonte_dados')
    op.drop_index('ix_software_dados_dataCriacao', table_name='software_dados')
    op.drop_index('ix_software_dados_dataLancamento', table_name='software_dados')
    op.drop_index('ix_software_dados_descricao', table_name='software_dados')
    op.drop_index('ix_software_dados_desenvolvimentoAtivo', table_name='software_dados')
    op.drop_index('ix_software_dados_licenca', table_name='software_dados')
    op.drop_index('ix_software_dados_linkDownload', table_name='software_dados')
    op.drop_index('ix_software_dados_proprietario', table_name='software_dados')
    op.drop_index('ix_software_dados_titulo', table_name='software_dados')
    op.drop_table('software_dados')
    op.drop_index('ix_user_description', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_tipo_usuario_nome', table_name='tipo_usuario')
    op.drop_table('tipo_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tipo_usuario_nome', 'tipo_usuario', ['nome'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_index('ix_user_description', 'user', ['description'], unique=False)
    op.create_table('software_dados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=70), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dataCriacao', sa.VARCHAR(length=10), nullable=True),
    sa.Column('dataLancamento', sa.VARCHAR(length=10), nullable=True),
    sa.Column('linkDownload', sa.VARCHAR(length=200), nullable=True),
    sa.Column('desenvolvimentoAtivo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('licenca', sa.VARCHAR(length=10), nullable=True),
    sa.Column('proprietario', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_software_dados_titulo', 'software_dados', ['titulo'], unique=False)
    op.create_index('ix_software_dados_proprietario', 'software_dados', ['proprietario'], unique=False)
    op.create_index('ix_software_dados_linkDownload', 'software_dados', ['linkDownload'], unique=False)
    op.create_index('ix_software_dados_licenca', 'software_dados', ['licenca'], unique=False)
    op.create_index('ix_software_dados_desenvolvimentoAtivo', 'software_dados', ['desenvolvimentoAtivo'], unique=False)
    op.create_index('ix_software_dados_descricao', 'software_dados', ['descricao'], unique=False)
    op.create_index('ix_software_dados_dataLancamento', 'software_dados', ['dataLancamento'], unique=False)
    op.create_index('ix_software_dados_dataCriacao', 'software_dados', ['dataCriacao'], unique=False)
    op.create_table('fonte_dados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=70), nullable=True),
    sa.Column('esfera', sa.VARCHAR(length=110), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=200), nullable=True),
    sa.Column('linkOficial', sa.VARCHAR(length=200), nullable=True),
    sa.Column('linkDataset', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fonte_dados_titulo', 'fonte_dados', ['titulo'], unique=False)
    op.create_index('ix_fonte_dados_linkOficial', 'fonte_dados', ['linkOficial'], unique=False)
    op.create_index('ix_fonte_dados_linkDataset', 'fonte_dados', ['linkDataset'], unique=False)
    op.create_index('ix_fonte_dados_esfera', 'fonte_dados', ['esfera'], unique=False)
    op.create_index('ix_fonte_dados_descricao', 'fonte_dados', ['descricao'], unique=False)
    op.drop_index(op.f('ix_softwares_title'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_owner'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_license'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_downloadLink'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_description'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_dateRelease'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_dateCreation'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_activeDevelopment'), table_name='softwares')
    op.drop_table('softwares')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_tag'), table_name='posts')
    op.drop_index(op.f('ix_posts_sphere'), table_name='posts')
    op.drop_index(op.f('ix_posts_officialLink'), table_name='posts')
    op.drop_index(op.f('ix_posts_description'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('followers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
