"""update

Revision ID: 4e185fc8c651
Revises: 2d37229f23db
Create Date: 2020-08-22 15:25:14.511265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e185fc8c651'
down_revision = '2d37229f23db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_category_source_id_source'), 'source', ['source_id'], ['id'])

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index('ix_source_category')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index('ix_source_category', ['category'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_source_id_source'), type_='foreignkey')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
