"""add table favorite

Revision ID: 4e44aa1c80c9
Revises: 2f190bc30eb5
Create Date: 2020-03-31 14:44:40.162186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e44aa1c80c9'
down_revision = '2f190bc30eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_post',
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['post.id'], )
    )
    op.create_table('favorites_software',
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['software.id'], )
    )
    op.drop_index('ix_favorito_gostei', table_name='favorito')
    op.drop_table('favorito')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.VARCHAR(length=600), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gostei', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favorito_gostei', 'favorito', ['gostei'], unique=False)
    op.drop_table('favorites_software')
    op.drop_table('favorites_post')
    # ### end Alembic commands ###
