"""user table

Revision ID: 51d33d300fde
Revises: 2896e96563e8
Create Date: 2019-11-02 21:08:15.900614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d33d300fde'
down_revision = '2896e96563e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_description'), 'user', ['description'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_usuario_apelido', table_name='usuario')
    op.drop_index('ix_usuario_descricao', table_name='usuario')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.drop_index('ix_usuario_nome', table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=70), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('senha', sa.VARCHAR(length=128), nullable=True),
    sa.Column('apelido', sa.VARCHAR(length=40), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuario_nome', 'usuario', ['nome'], unique=1)
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=1)
    op.create_index('ix_usuario_descricao', 'usuario', ['descricao'], unique=False)
    op.create_index('ix_usuario_apelido', 'usuario', ['apelido'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_description'), table_name='user')
    op.drop_table('user')
    op.drop_table('categoria')
    # ### end Alembic commands ###
