"""fiz os relacionamentos de software, user, source

Revision ID: 58c02f849e10
Revises: b95f589286bb
Create Date: 2019-11-13 22:05:10.201248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c02f849e10'
down_revision = 'b95f589286bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.create_foreign_key(None, 'software', 'user', ['userSoftware_id'], ['id'])
    op.drop_column('software', 'user_id')
    op.add_column('source', sa.Column('userSource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'source', 'user', ['userSource_id'], ['id'])
    op.drop_column('source', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_column('source', 'userSource_id')
    op.add_column('software', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.create_foreign_key(None, 'software', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
