"""update software

Revision ID: 5a93ea4b5ade
Revises: 8373eb55e977
Create Date: 2020-07-23 17:24:12.769852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a93ea4b5ade'
down_revision = '8373eb55e977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officialLink', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_software_officialLink'), ['officialLink'], unique=False)
        batch_op.drop_index('ix_software_activeDevelopment')
        batch_op.drop_index('ix_software_dateRelease')
        batch_op.drop_index('ix_software_downloadLink')
        batch_op.drop_column('activeDevelopment')
        batch_op.drop_column('downloadLink')
        batch_op.drop_column('dateRelease')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateRelease', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('downloadLink', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('activeDevelopment', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index('ix_software_downloadLink', ['downloadLink'], unique=False)
        batch_op.create_index('ix_software_dateRelease', ['dateRelease'], unique=False)
        batch_op.create_index('ix_software_activeDevelopment', ['activeDevelopment'], unique=False)
        batch_op.drop_index(batch_op.f('ix_software_officialLink'))
        batch_op.drop_column('officialLink')

    # ### end Alembic commands ###
