"""posts tag

Revision ID: 5e68ccd9be04
Revises: 93a039642054
Create Date: 2020-03-18 19:15:45.690748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e68ccd9be04'
down_revision = '93a039642054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_softwares_dateRelease'), 'softwares', ['dateRelease'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_softwares_dateRelease'), table_name='softwares')
    # ### end Alembic commands ###
