"""relacionamentos user e source

Revision ID: 5f6478ccc7a4
Revises: 76fe7187e562
Create Date: 2019-11-11 00:23:10.229426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6478ccc7a4'
down_revision = '76fe7187e562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'source', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    # ### end Alembic commands ###
