"""add similar

Revision ID: 61cb66d1521d
Revises: 007880519ca8
Create Date: 2020-08-03 15:52:16.210889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cb66d1521d'
down_revision = '007880519ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.drop_index('ix_similar_name')
        batch_op.drop_index('ix_similar_timestamp')

    op.drop_table('similar')
    op.drop_table('favorites_post')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_similar'), ['similar'], unique=False)

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_software_similar'), ['similar'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_similar'))
        batch_op.drop_column('similar')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_similar'))
        batch_op.drop_column('similar')

    op.create_table('favorites_post',
    sa.Column('favorite_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['post.id'], name='fk_favorites_post_favorite_id_post')
    )
    op.create_table('similar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('software_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_similar_post_id_post'),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name='fk_similar_software_id_software'),
    sa.PrimaryKeyConstraint('id', name='pk_similar')
    )
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.create_index('ix_similar_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_similar_name', ['name'], unique=False)

    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='fk_followers_followed_id_user'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='fk_followers_follower_id_user')
    )
    # ### end Alembic commands ###
