"""update id moodels

Revision ID: 65b94bac54f8
Revises: e956818b4979
Create Date: 2020-09-22 20:20:01.803304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b94bac54f8'
down_revision = 'e956818b4979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_source_id_source', type_='foreignkey')
        batch_op.drop_constraint('fk_category_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_category_source_id_source'), 'source', ['source_id'], ['id_source'])
        batch_op.create_foreign_key(batch_op.f('fk_category_software_id_software'), 'software', ['software_id'], ['id_software'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_source_id_source', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_software_id_software'), 'software', ['software_id'], ['id_software'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_source_id_source'), 'source', ['source_id'], ['id_source'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_source_id_source', type_='foreignkey')
        batch_op.drop_constraint('fk_report_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_report_source_id_source'), 'source', ['source_id'], ['id_source'])
        batch_op.create_foreign_key(batch_op.f('fk_report_software_id_software'), 'software', ['software_id'], ['id_software'])

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_software', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_source', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tag_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_source_id_source', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tag_software_id_software'), 'software', ['software_id'], ['id_software'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_source_id_source'), 'source', ['source_id'], ['id_source'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tag_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_software_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tag_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_tag_software_id_software', 'software', ['software_id'], ['id'])

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id_source')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id_software')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_report_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_report_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_report_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_report_source_id_source', 'source', ['source_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_software_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_software_id_software', 'software', ['software_id'], ['id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_category_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_category_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_category_source_id_source', 'source', ['source_id'], ['id'])

    # ### end Alembic commands ###
