"""update

Revision ID: 673ce29f85d2
Revises: 663c60a863bb
Create Date: 2020-08-22 13:40:43.063688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673ce29f85d2'
down_revision = '663c60a863bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_categories_category_id_category')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_categories_source_id_source')),
    sa.PrimaryKeyConstraint('category_id', 'source_id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_timestamp')
        batch_op.drop_constraint('fk_category_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_category_source_id_source', type_='foreignkey')
        batch_op.drop_column('source_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_category_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_category_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_index('ix_category_timestamp', ['timestamp'], unique=False)

    op.drop_table('categories')
    # ### end Alembic commands ###
