"""atualizei software

Revision ID: 6909a29c2b38
Revises: 6bcae0caaafe
Create Date: 2020-03-24 02:02:34.508464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6909a29c2b38'
down_revision = '6bcae0caaafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_softwares_dateRelease'), 'softwares', ['dateRelease'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_softwares_dateRelease'), table_name='softwares')
    # ### end Alembic commands ###
