"""add table foreingKey tag and category

Revision ID: 6ace8eed9708
Revises: 3a51db76ae60
Create Date: 2020-08-20 02:00:27.030469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ace8eed9708'
down_revision = '3a51db76ae60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_category_source_id_source'), 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_category_software_id_software'), 'software', ['software_id'], ['id'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tag_software_id_software'), 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_source_id_source'), 'source', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tag_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_software_id_software'), type_='foreignkey')
        batch_op.drop_column('source_id')
        batch_op.drop_column('software_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_category_source_id_source'), type_='foreignkey')
        batch_op.drop_column('source_id')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###
