"""delete data relase software

Revision ID: 6bcae0caaafe
Revises: 6d019323ee09
Create Date: 2020-03-24 01:58:03.703872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcae0caaafe'
down_revision = '6d019323ee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_softwares_dateRelease', table_name='softwares')
    op.drop_column('softwares', 'dateRelease')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('dateRelease', sa.VARCHAR(length=300), nullable=True))
    op.create_index('ix_softwares_dateRelease', 'softwares', ['dateRelease'], unique=False)
    # ### end Alembic commands ###
