"""add categorie

Revision ID: 6d019323ee09
Revises: 1844fd07f797
Create Date: 2020-03-24 01:56:28.651170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d019323ee09'
down_revision = '1844fd07f797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categorie', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_posts_categorie'), 'posts', ['categorie'], unique=False)
    op.drop_index('ix_posts_tag', table_name='posts')
    op.create_index(op.f('ix_posts_tag'), 'posts', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_tag'), table_name='posts')
    op.create_index('ix_posts_tag', 'posts', ['tag'], unique=1)
    op.drop_index(op.f('ix_posts_categorie'), table_name='posts')
    op.drop_column('posts', 'categorie')
    # ### end Alembic commands ###
