"""atualizei nome source

Revision ID: 6e4e57c80338
Revises: c0febca6dd1f
Create Date: 2020-08-19 19:37:46.342030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4e57c80338'
down_revision = 'c0febca6dd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_source_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_officialLink'), ['officialLink'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_sphere'), ['sphere'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_title'), ['title'], unique=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_category')
        batch_op.drop_index('ix_post_city')
        batch_op.drop_index('ix_post_country')
        batch_op.drop_index('ix_post_description')
        batch_op.drop_index('ix_post_officialLink')
        batch_op.drop_index('ix_post_sphere')
        batch_op.drop_index('ix_post_state')
        batch_op.drop_index('ix_post_tag')
        batch_op.drop_index('ix_post_timestamp')
        batch_op.drop_index('ix_post_title')

    op.drop_table('post')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_report_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_report_source_id_source'), 'source', ['source_id'], ['id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_similar_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_similar_source_id_source'), 'source', ['source_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_similar_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_similar_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.drop_column('source_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_report_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_report_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.drop_column('source_id')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=200), nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sphere', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=200), nullable=True),
    sa.Column('state', sa.VARCHAR(length=200), nullable=True),
    sa.Column('country', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), nullable=True),
    sa.Column('officialLink', sa.VARCHAR(length=300), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_post')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_title', ['title'], unique=1)
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_post_tag', ['tag'], unique=False)
        batch_op.create_index('ix_post_state', ['state'], unique=False)
        batch_op.create_index('ix_post_sphere', ['sphere'], unique=False)
        batch_op.create_index('ix_post_officialLink', ['officialLink'], unique=False)
        batch_op.create_index('ix_post_description', ['description'], unique=False)
        batch_op.create_index('ix_post_country', ['country'], unique=False)
        batch_op.create_index('ix_post_city', ['city'], unique=False)
        batch_op.create_index('ix_post_category', ['category'], unique=False)

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_title'))
        batch_op.drop_index(batch_op.f('ix_source_timestamp'))
        batch_op.drop_index(batch_op.f('ix_source_tag'))
        batch_op.drop_index(batch_op.f('ix_source_state'))
        batch_op.drop_index(batch_op.f('ix_source_sphere'))
        batch_op.drop_index(batch_op.f('ix_source_officialLink'))
        batch_op.drop_index(batch_op.f('ix_source_description'))
        batch_op.drop_index(batch_op.f('ix_source_country'))
        batch_op.drop_index(batch_op.f('ix_source_city'))
        batch_op.drop_index(batch_op.f('ix_source_category'))

    op.drop_table('source')
    # ### end Alembic commands ###
