"""posts and softwares

Revision ID: 7040ce8985c8
Revises: 796e5f01823f
Create Date: 2020-03-18 19:08:42.038030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7040ce8985c8'
down_revision = '796e5f01823f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('softwares', 'dateRelease')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('dateRelease', sa.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
