"""table comment

Revision ID: 74fca437392e
Revises: 2a981d0ffda1
Create Date: 2020-03-26 22:54:13.549935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fca437392e'
down_revision = '2a981d0ffda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=600), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_comment'), 'comment', ['comment'], unique=False)
    op.create_index(op.f('ix_comment_email'), 'comment', ['email'], unique=False)
    op.create_index(op.f('ix_comment_name'), 'comment', ['name'], unique=False)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.drop_index('ix_comentario_data', table_name='comentario')
    op.drop_index('ix_comentario_texto', table_name='comentario')
    op.drop_table('comentario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=200), nullable=True),
    sa.Column('texto', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comentario_texto', 'comentario', ['texto'], unique=False)
    op.create_index('ix_comentario_data', 'comentario', ['data'], unique=False)
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_index(op.f('ix_comment_name'), table_name='comment')
    op.drop_index(op.f('ix_comment_email'), table_name='comment')
    op.drop_index(op.f('ix_comment_comment'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
