"""relacionamentos user e source

Revision ID: 76fe7187e562
Revises: 49938ad6c2d9
Create Date: 2019-11-11 00:16:43.373197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fe7187e562'
down_revision = '49938ad6c2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_source_timestamp'), 'source', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'source', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_index(op.f('ix_source_timestamp'), table_name='source')
    op.drop_column('source', 'user_id')
    op.drop_column('source', 'timestamp')
    # ### end Alembic commands ###
