"""posts and softwares

Revision ID: 796e5f01823f
Revises: c2551e24ef9c
Create Date: 2020-03-18 19:00:06.444824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796e5f01823f'
down_revision = 'c2551e24ef9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_description'), 'posts', ['description'], unique=False)
    op.create_index(op.f('ix_posts_officialLink'), 'posts', ['officialLink'], unique=False)
    op.create_index(op.f('ix_posts_sphere'), 'posts', ['sphere'], unique=False)
    op.create_index(op.f('ix_posts_tag'), 'posts', ['tag'], unique=True)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=True)
    op.drop_index('ix_sources_datasetLink', table_name='sources')
    op.drop_index('ix_sources_description', table_name='sources')
    op.drop_index('ix_sources_officialLink', table_name='sources')
    op.drop_index('ix_sources_sphere', table_name='sources')
    op.drop_index('ix_sources_timestamp', table_name='sources')
    op.drop_index('ix_sources_title', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_softwares_dateRelease', table_name='softwares')
    op.drop_column('softwares', 'dateRelease')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('dateRelease', sa.VARCHAR(length=300), nullable=True))
    op.create_index('ix_softwares_dateRelease', 'softwares', ['dateRelease'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sphere', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.VARCHAR(length=800), nullable=True),
    sa.Column('officialLink', sa.VARCHAR(length=300), nullable=True),
    sa.Column('datasetLink', sa.VARCHAR(length=300), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_title', 'sources', ['title'], unique=1)
    op.create_index('ix_sources_timestamp', 'sources', ['timestamp'], unique=False)
    op.create_index('ix_sources_sphere', 'sources', ['sphere'], unique=False)
    op.create_index('ix_sources_officialLink', 'sources', ['officialLink'], unique=False)
    op.create_index('ix_sources_description', 'sources', ['description'], unique=False)
    op.create_index('ix_sources_datasetLink', 'sources', ['datasetLink'], unique=False)
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_tag'), table_name='posts')
    op.drop_index(op.f('ix_posts_sphere'), table_name='posts')
    op.drop_index(op.f('ix_posts_officialLink'), table_name='posts')
    op.drop_index(op.f('ix_posts_description'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
