"""update bd

Revision ID: 7cd73a6d31d7
Revises: d714eb4bcd42
Create Date: 2020-10-22 19:12:28.443081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd73a6d31d7'
down_revision = 'd714eb4bcd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('fk_similar_software_id_software')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_similar_source_id_source'))
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], name=op.f('fk_tags_software_id_software')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_tags_source_id_source')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tags_tag_id_tag'))
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_tag_keyword'), ['keyword'], unique=False)
        batch_op.drop_index('ix_tag_tag')
        batch_op.drop_constraint('fk_tag_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_source_id_source', type_='foreignkey')
        batch_op.drop_column('tag')
        batch_op.drop_column('software_id')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_foreign_key('fk_tag_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_tag_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_index('ix_tag_tag', ['tag'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tag_keyword'))
        batch_op.drop_column('keyword')

    op.drop_table('tags')
    op.drop_table('similar')
    # ### end Alembic commands ###
