"""update tagging

Revision ID: 7dbd1ed198bc
Revises: b50ac8e92a72
Create Date: 2020-10-19 20:05:00.326262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbd1ed198bc'
down_revision = 'b50ac8e92a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tags_software_id_software', type_='foreignkey')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_tags_software_id_software', 'software', ['software_id'], ['id'])

    # ### end Alembic commands ###
