"""relacionamentos software, user, source

Revision ID: 832217c0e515
Revises: 7e0e3fef043b
Create Date: 2019-11-11 00:43:18.493980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832217c0e515'
down_revision = '7e0e3fef043b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('downloadLink', sa.String(length=300), nullable=True),
    sa.Column('activeDevelopment', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('dateCreation', sa.String(length=300), nullable=True),
    sa.Column('dateRelease', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_activeDevelopment'), 'software', ['activeDevelopment'], unique=False)
    op.create_index(op.f('ix_software_dateCreation'), 'software', ['dateCreation'], unique=False)
    op.create_index(op.f('ix_software_dateRelease'), 'software', ['dateRelease'], unique=False)
    op.create_index(op.f('ix_software_description'), 'software', ['description'], unique=False)
    op.create_index(op.f('ix_software_downloadLink'), 'software', ['downloadLink'], unique=False)
    op.create_index(op.f('ix_software_license'), 'software', ['license'], unique=False)
    op.create_index(op.f('ix_software_owner'), 'software', ['owner'], unique=False)
    op.create_index(op.f('ix_software_title'), 'software', ['title'], unique=False)
    op.drop_index('ix_software_dados_dataCriacao', table_name='software_dados')
    op.drop_index('ix_software_dados_dataLancamento', table_name='software_dados')
    op.drop_index('ix_software_dados_descricao', table_name='software_dados')
    op.drop_index('ix_software_dados_desenvolvimentoAtivo', table_name='software_dados')
    op.drop_index('ix_software_dados_licenca', table_name='software_dados')
    op.drop_index('ix_software_dados_linkDownload', table_name='software_dados')
    op.drop_index('ix_software_dados_proprietario', table_name='software_dados')
    op.drop_index('ix_software_dados_titulo', table_name='software_dados')
    op.drop_table('software_dados')
    op.create_foreign_key(None, 'source', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.create_table('software_dados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=500), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=500), nullable=True),
    sa.Column('dataCriacao', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dataLancamento', sa.VARCHAR(length=200), nullable=True),
    sa.Column('linkDownload', sa.VARCHAR(length=500), nullable=True),
    sa.Column('desenvolvimentoAtivo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('licenca', sa.VARCHAR(length=200), nullable=True),
    sa.Column('proprietario', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_software_dados_titulo', 'software_dados', ['titulo'], unique=False)
    op.create_index('ix_software_dados_proprietario', 'software_dados', ['proprietario'], unique=False)
    op.create_index('ix_software_dados_linkDownload', 'software_dados', ['linkDownload'], unique=False)
    op.create_index('ix_software_dados_licenca', 'software_dados', ['licenca'], unique=False)
    op.create_index('ix_software_dados_desenvolvimentoAtivo', 'software_dados', ['desenvolvimentoAtivo'], unique=False)
    op.create_index('ix_software_dados_descricao', 'software_dados', ['descricao'], unique=False)
    op.create_index('ix_software_dados_dataLancamento', 'software_dados', ['dataLancamento'], unique=False)
    op.create_index('ix_software_dados_dataCriacao', 'software_dados', ['dataCriacao'], unique=False)
    op.drop_index(op.f('ix_software_title'), table_name='software')
    op.drop_index(op.f('ix_software_owner'), table_name='software')
    op.drop_index(op.f('ix_software_license'), table_name='software')
    op.drop_index(op.f('ix_software_downloadLink'), table_name='software')
    op.drop_index(op.f('ix_software_description'), table_name='software')
    op.drop_index(op.f('ix_software_dateRelease'), table_name='software')
    op.drop_index(op.f('ix_software_dateCreation'), table_name='software')
    op.drop_index(op.f('ix_software_activeDevelopment'), table_name='software')
    op.drop_table('software')
    # ### end Alembic commands ###
