"""select index

Revision ID: 8a454e7b5527
Revises: 8cc3373c1b38
Create Date: 2019-11-25 22:23:10.467245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a454e7b5527'
down_revision = '8cc3373c1b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_data'), 'comentario', ['data'], unique=False)
    op.create_index(op.f('ix_comentario_texto'), 'comentario', ['texto'], unique=False)
    op.create_table('denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denuncia_descricao'), 'denuncia', ['descricao'], unique=False)
    op.create_index(op.f('ix_denuncia_tipo'), 'denuncia', ['tipo'], unique=False)
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gostei', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorito_gostei'), 'favorito', ['gostei'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palavraChave', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_palavraChave'), 'tag', ['palavraChave'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.Column('about_me', sa.String(length=300), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('typeUser', sa.String(length=200), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('softwares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('downloadLink', sa.String(length=300), nullable=True),
    sa.Column('activeDevelopment', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('dateCreation', sa.String(length=300), nullable=True),
    sa.Column('dateRelease', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_softwares_activeDevelopment'), 'softwares', ['activeDevelopment'], unique=False)
    op.create_index(op.f('ix_softwares_dateCreation'), 'softwares', ['dateCreation'], unique=False)
    op.create_index(op.f('ix_softwares_dateRelease'), 'softwares', ['dateRelease'], unique=False)
    op.create_index(op.f('ix_softwares_description'), 'softwares', ['description'], unique=False)
    op.create_index(op.f('ix_softwares_downloadLink'), 'softwares', ['downloadLink'], unique=False)
    op.create_index(op.f('ix_softwares_license'), 'softwares', ['license'], unique=False)
    op.create_index(op.f('ix_softwares_owner'), 'softwares', ['owner'], unique=False)
    op.create_index(op.f('ix_softwares_title'), 'softwares', ['title'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=300), nullable=True),
    sa.Column('datasetLink', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_datasetLink'), 'sources', ['datasetLink'], unique=False)
    op.create_index(op.f('ix_sources_description'), 'sources', ['description'], unique=False)
    op.create_index(op.f('ix_sources_officialLink'), 'sources', ['officialLink'], unique=False)
    op.create_index(op.f('ix_sources_sphere'), 'sources', ['sphere'], unique=False)
    op.create_index(op.f('ix_sources_timestamp'), 'sources', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sources_title'), 'sources', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_title'), table_name='sources')
    op.drop_index(op.f('ix_sources_timestamp'), table_name='sources')
    op.drop_index(op.f('ix_sources_sphere'), table_name='sources')
    op.drop_index(op.f('ix_sources_officialLink'), table_name='sources')
    op.drop_index(op.f('ix_sources_description'), table_name='sources')
    op.drop_index(op.f('ix_sources_datasetLink'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_softwares_title'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_owner'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_license'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_downloadLink'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_description'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_dateRelease'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_dateCreation'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_activeDevelopment'), table_name='softwares')
    op.drop_table('softwares')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tag_palavraChave'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_favorito_gostei'), table_name='favorito')
    op.drop_table('favorito')
    op.drop_index(op.f('ix_denuncia_tipo'), table_name='denuncia')
    op.drop_index(op.f('ix_denuncia_descricao'), table_name='denuncia')
    op.drop_table('denuncia')
    op.drop_index(op.f('ix_comentario_texto'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_data'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
