"""softwares

Revision ID: 93a039642054
Revises: c8d93aa46fe8
Create Date: 2020-03-18 19:12:24.739212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a039642054'
down_revision = 'c8d93aa46fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_softwares_dateRelease', table_name='softwares')
    op.drop_column('softwares', 'dateRelease')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('dateRelease', sa.VARCHAR(length=300), nullable=True))
    op.create_index('ix_softwares_dateRelease', 'softwares', ['dateRelease'], unique=False)
    # ### end Alembic commands ###
