"""update

Revision ID: a03c3ef023db
Revises: 3f8d4febc7b9
Create Date: 2020-08-22 22:01:32.310645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03c3ef023db'
down_revision = '3f8d4febc7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_tag_software_tag_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_source_tag_id_source', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tag_software_id_software'), 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_source_id_source'), 'source', ['source_id'], ['id'])
        batch_op.drop_column('source_tag_id')
        batch_op.drop_column('software_tag_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_tag_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('source_tag_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tag_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_software_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tag_source_tag_id_source', 'source', ['source_tag_id'], ['id'])
        batch_op.create_foreign_key('fk_tag_software_tag_id_software', 'software', ['software_tag_id'], ['id'])
        batch_op.drop_column('source_id')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###
