"""tabela login

Revision ID: ac5f6900c852
Revises: 
Create Date: 2019-10-14 23:21:25.594936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5f6900c852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_email'), 'login', ['email'], unique=True)
    op.create_index(op.f('ix_login_nome'), 'login', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_nome'), table_name='login')
    op.drop_index(op.f('ix_login_email'), table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###
