"""atualizei tabela user

Revision ID: b3362ea95a51
Revises: bcc41960fe3c
Create Date: 2020-09-29 17:19:18.975248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3362ea95a51'
down_revision = 'bcc41960fe3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_nickname'), ['nickname'], unique=True)
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_index(batch_op.f('ix_user_nickname'))

    # ### end Alembic commands ###
