"""tag N pra N

Revision ID: b92f8dc500b2
Revises: 254beea8eec1
Create Date: 2020-10-11 00:52:27.317444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92f8dc500b2'
down_revision = '254beea8eec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_tag', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source_tag', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_tags_source_id_source', type_='foreignkey')
        batch_op.drop_constraint('fk_tags_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tags_source_tag_source'), 'source', ['source_tag'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tags_software_tag_software'), 'software', ['software_tag'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_tags_software_tag_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tags_source_tag_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tags_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_tags_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.drop_column('source_tag')
        batch_op.drop_column('software_tag')

    # ### end Alembic commands ###
