"""relacionamentos software, user, source

Revision ID: b95f589286bb
Revises: ff873d80fbb1
Create Date: 2019-11-13 22:00:28.853424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95f589286bb'
down_revision = 'ff873d80fbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.drop_index('ix_usuario_username', table_name='usuario')
    op.drop_table('usuario')
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.drop_column('software', 'user_id')
    op.drop_column('software', 'userSoftware_id')
    op.add_column('source', sa.Column('userSource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'source', 'user', ['userSource_id'], ['id'])
    op.drop_column('source', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_column('source', 'userSource_id')
    op.add_column('software', sa.Column('userSoftware_id', sa.INTEGER(), nullable=True))
    op.add_column('software', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'software', 'user', ['user_id'], ['id'])
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=150), nullable=True),
    sa.Column('about_me', sa.VARCHAR(length=300), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuario_username', 'usuario', ['username'], unique=1)
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=1)
    # ### end Alembic commands ###
