"""update db

Revision ID: bdceaac98067
Revises: 247eaf5a09f0
Create Date: 2020-08-21 21:12:09.989499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdceaac98067'
down_revision = '247eaf5a09f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('ix_message_timestamp')

    op.drop_table('message')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_category_source_id_source', type_='foreignkey')
        batch_op.drop_column('software_id')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_software_tag_id_tag'), 'tag', ['tag_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_software_category_id_category'), 'category', ['category_id'], ['id'])

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_source_tag_id_tag'), 'tag', ['tag_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_source_category_id_category'), 'category', ['category_id'], ['id'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tag_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_source_id_source', type_='foreignkey')
        batch_op.drop_column('software_id')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_tag_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_tag_software_id_software', 'software', ['software_id'], ['id'])

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_source_category_id_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_source_tag_id_tag'), type_='foreignkey')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_software_category_id_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_software_tag_id_tag'), type_='foreignkey')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_category_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_category_software_id_software', 'software', ['software_id'], ['id'])

    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='fk_message_recipient_id_user'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='fk_message_sender_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_message')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('ix_message_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
