"""atualizei tabela comments

Revision ID: c0febca6dd1f
Revises: 8672954ac9b6
Create Date: 2020-08-19 02:20:34.612549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0febca6dd1f'
down_revision = '8672954ac9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_post_id_post', type_='foreignkey')
        batch_op.drop_column('post_id')
        batch_op.drop_column('software_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_comment_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_comment_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
