"""tables update

Revision ID: c1a818822b43
Revises: e424f2ecfeae
Create Date: 2020-07-23 22:27:52.841677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a818822b43'
down_revision = 'e424f2ecfeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_tag')
        batch_op.drop_index('ix_tag_timestamp')

    op.drop_table('tag')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_category')
        batch_op.drop_index('ix_category_timestamp')

    op.drop_table('category')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('City', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_City'), ['City'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_tag'), ['tag'], unique=False)

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_software_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_tag'), ['tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_tag'))
        batch_op.drop_index(batch_op.f('ix_software_category'))
        batch_op.drop_column('tag')
        batch_op.drop_column('category')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_tag'))
        batch_op.drop_index(batch_op.f('ix_post_state'))
        batch_op.drop_index(batch_op.f('ix_post_country'))
        batch_op.drop_index(batch_op.f('ix_post_category'))
        batch_op.drop_index(batch_op.f('ix_post_City'))
        batch_op.drop_column('tag')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('category')
        batch_op.drop_column('City')

    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('postCategory_id', sa.INTEGER(), nullable=True),
    sa.Column('softwareCategory_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['postCategory_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['softwareCategory_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_category')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('ix_category_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_category_category', ['category'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('postTag_id', sa.INTEGER(), nullable=True),
    sa.Column('softwareTag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['postTag_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['softwareTag_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_tag')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('ix_tag_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_tag_tag', ['tag'], unique=False)

    # ### end Alembic commands ###
