"""empty message

Revision ID: c433e100a3a8
Revises: 14dded2ed444
Create Date: 2019-11-08 22:10:48.131216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c433e100a3a8'
down_revision = '14dded2ed444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_description', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_column('user', 'description')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=200), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('description', sa.VARCHAR(length=500), nullable=True))
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=False)
    op.create_index('ix_user_description', 'user', ['description'], unique=False)
    # ### end Alembic commands ###
