"""atualizei tabelas

Revision ID: c5145d328bf8
Revises: 0157afb9a9cb
Create Date: 2020-08-01 18:23:02.744618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5145d328bf8'
down_revision = '0157afb9a9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_post_id_post'), 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_software_id_software'), 'software', ['software_id'], ['id'])
        batch_op.drop_column('postComment_id')
        batch_op.drop_column('softwareComment_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_report_post_id_post'), 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_report_software_id_software'), 'software', ['software_id'], ['id'])
        batch_op.drop_column('postReport_id')
        batch_op.drop_column('softwareReport_id')

    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_similar_post_id_post'), 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_similar_software_id_software'), 'software', ['software_id'], ['id'])
        batch_op.drop_column('softwareSimilar_id')
        batch_op.drop_column('postSimilar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postSimilar_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('softwareSimilar_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_similar_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_similar_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'software', ['softwareSimilar_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['postSimilar_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('softwareReport_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('postReport_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_report_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_report_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['postReport_id'], ['id'])
        batch_op.create_foreign_key(None, 'software', ['softwareReport_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('softwareComment_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('postComment_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comment_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['postComment_id'], ['id'])
        batch_op.create_foreign_key(None, 'software', ['softwareComment_id'], ['id'])
        batch_op.drop_column('software_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
