"""relacionamentos software, user, source

Revision ID: c5f630a4e173
Revises: 08a0d16b99c7
Create Date: 2019-11-11 00:55:18.754382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f630a4e173'
down_revision = '08a0d16b99c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userSoftware_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_software_title')
        batch_op.create_index(batch_op.f('ix_software_title'), ['title'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userSoftware_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userSource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['userSource_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userSource_id')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_software_title'))
        batch_op.create_index('ix_software_title', ['title'], unique=False)
        batch_op.drop_column('userSoftware_id')

    # ### end Alembic commands ###
