"""table source

Revision ID: cabdb28e0cdc
Revises: bfcceb9a3ffd
Create Date: 2019-11-09 21:50:08.894661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabdb28e0cdc'
down_revision = 'bfcceb9a3ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('sphere', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=800), nullable=True),
    sa.Column('officialLink', sa.String(length=250), nullable=True),
    sa.Column('datasetLink', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_datasetLink'), 'source', ['datasetLink'], unique=False)
    op.create_index(op.f('ix_source_description'), 'source', ['description'], unique=False)
    op.create_index(op.f('ix_source_officialLink'), 'source', ['officialLink'], unique=False)
    op.create_index(op.f('ix_source_sphere'), 'source', ['sphere'], unique=False)
    op.create_index(op.f('ix_source_title'), 'source', ['title'], unique=True)
    op.drop_index('ix_fonte_dados_descricao', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_esfera', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_linkDataset', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_linkOficial', table_name='fonte_dados')
    op.drop_index('ix_fonte_dados_titulo', table_name='fonte_dados')
    op.drop_table('fonte_dados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonte_dados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=500), nullable=True),
    sa.Column('esfera', sa.VARCHAR(length=150), nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=500), nullable=True),
    sa.Column('linkOficial', sa.VARCHAR(length=500), nullable=True),
    sa.Column('linkDataset', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fonte_dados_titulo', 'fonte_dados', ['titulo'], unique=False)
    op.create_index('ix_fonte_dados_linkOficial', 'fonte_dados', ['linkOficial'], unique=False)
    op.create_index('ix_fonte_dados_linkDataset', 'fonte_dados', ['linkDataset'], unique=False)
    op.create_index('ix_fonte_dados_esfera', 'fonte_dados', ['esfera'], unique=False)
    op.create_index('ix_fonte_dados_descricao', 'fonte_dados', ['descricao'], unique=False)
    op.drop_index(op.f('ix_source_title'), table_name='source')
    op.drop_index(op.f('ix_source_sphere'), table_name='source')
    op.drop_index(op.f('ix_source_officialLink'), table_name='source')
    op.drop_index(op.f('ix_source_description'), table_name='source')
    op.drop_index(op.f('ix_source_datasetLink'), table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###
