"""update

Revision ID: cd89ff512136
Revises: 4d00f36a7ef6
Create Date: 2020-08-22 01:35:34.271714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd89ff512136'
down_revision = '4d00f36a7ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_category_software_category_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_category_source_category_id_source', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_category_source_id_source'), 'source', ['source_id'], ['id'])
        batch_op.drop_column('source_category_id')
        batch_op.drop_column('software_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('source_category_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_category_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_category_source_category_id_source', 'source', ['source_category_id'], ['id'])
        batch_op.create_foreign_key('fk_category_software_category_id_software', 'software', ['software_category_id'], ['id'])
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
