"""teste

Revision ID: d0f662810095
Revises: 0b837162b000
Create Date: 2020-07-08 22:05:39.740551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f662810095'
down_revision = '0b837162b000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'comment')
    op.add_column('similar', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('similar', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_similar_timestamp'), 'similar', ['timestamp'], unique=False)
    op.drop_index('ix_similar_name', table_name='similar')
    op.create_index(op.f('ix_similar_name'), 'similar', ['name'], unique=False)
    op.create_foreign_key(None, 'similar', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'similar', type_='foreignkey')
    op.drop_index(op.f('ix_similar_name'), table_name='similar')
    op.create_index('ix_similar_name', 'similar', ['name'], unique=1)
    op.drop_index(op.f('ix_similar_timestamp'), table_name='similar')
    op.drop_column('similar', 'timestamp')
    op.drop_column('similar', 'post_id')
    op.add_column('comment', sa.Column('comment', sa.VARCHAR(length=600), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    # ### end Alembic commands ###
