"""criei tabelas e resolvi bug

Revision ID: e9a2c830755e
Revises: 4caa86c3f7d6
Create Date: 2019-11-19 10:44:03.184622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a2c830755e'
down_revision = '4caa86c3f7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_softwares_activeDevelopment'), 'softwares', ['activeDevelopment'], unique=False)
    op.create_index(op.f('ix_softwares_dateCreation'), 'softwares', ['dateCreation'], unique=False)
    op.create_index(op.f('ix_softwares_dateRelease'), 'softwares', ['dateRelease'], unique=False)
    op.create_index(op.f('ix_softwares_downloadLink'), 'softwares', ['downloadLink'], unique=False)
    op.drop_index('ix_softwares_activeDevelopment', table_name='softwares')
    op.drop_index('ix_softwares_dateCreation', table_name='softwares')
    op.drop_index('ix_softwares_dateRelease', table_name='softwares')
    op.drop_index('ix_softwares_downloadLink', table_name='softwares')
    op.create_index(op.f('ix_sources_datasetLink'), 'sources', ['datasetLink'], unique=False)
    op.create_index(op.f('ix_sources_officialLink'), 'sources', ['officialLink'], unique=False)
    op.drop_index('ix_sources_datasetLink', table_name='sources')
    op.drop_index('ix_sources_officialLink', table_name='sources')
    op.create_index(op.f('ix_tag_palavraChave'), 'tag', ['palavraChave'], unique=False)
    op.drop_index('ix_tag_palavraChave', table_name='tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tag_palavraChave', 'tag', ['palavraChave'], unique=False)
    op.drop_index(op.f('ix_tag_palavraChave'), table_name='tag')
    op.create_index('ix_sources_officialLink', 'sources', ['officialLink'], unique=False)
    op.create_index('ix_sources_datasetLink', 'sources', ['datasetLink'], unique=False)
    op.drop_index(op.f('ix_sources_officialLink'), table_name='sources')
    op.drop_index(op.f('ix_sources_datasetLink'), table_name='sources')
    op.create_index('ix_softwares_downloadLink', 'softwares', ['downloadLink'], unique=False)
    op.create_index('ix_softwares_dateRelease', 'softwares', ['dateRelease'], unique=False)
    op.create_index('ix_softwares_dateCreation', 'softwares', ['dateCreation'], unique=False)
    op.create_index('ix_softwares_activeDevelopment', 'softwares', ['activeDevelopment'], unique=False)
    op.drop_index(op.f('ix_softwares_downloadLink'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_dateRelease'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_dateCreation'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_activeDevelopment'), table_name='softwares')
    # ### end Alembic commands ###
