"""post reference user

Revision ID: e9d3a715514c
Revises: 410b133dbfb2
Create Date: 2020-07-09 23:30:55.453425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d3a715514c'
down_revision = '410b133dbfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_post_id_post'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_post_id_post'), type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
