"""Usuario

Revision ID: ef9b98b18a9a
Revises: ac5f6900c852
Create Date: 2019-10-20 21:06:29.201396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9b98b18a9a'
down_revision = 'ac5f6900c852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.Column('apelido', sa.String(length=40), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_apelido'), 'usuario', ['apelido'], unique=False)
    op.create_index(op.f('ix_usuario_descricao'), 'usuario', ['descricao'], unique=False)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    op.drop_index('ix_login_email', table_name='login')
    op.drop_index('ix_login_nome', table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=70), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('senha', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_nome', 'login', ['nome'], unique=1)
    op.create_index('ix_login_email', 'login', ['email'], unique=1)
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_descricao'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_apelido'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
