"""update

Revision ID: f007854edd8a
Revises: 338e85c4c9e3
Create Date: 2020-09-21 18:46:31.778728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f007854edd8a'
down_revision = '338e85c4c9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_category_source_id_source', type_='foreignkey')
        batch_op.drop_constraint('fk_category_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_category_source_id_source'), 'source', ['source_id'], ['source_id'])
        batch_op.create_foreign_key(batch_op.f('fk_category_software_id_software'), 'software', ['software_id'], ['software_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_software_id_software'), 'software', ['software_id'], ['software_id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_source_id_source'), 'source', ['source_id'], ['source_id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_source_id_source', type_='foreignkey')
        batch_op.drop_constraint('fk_report_software_id_software', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_report_software_id_software'), 'software', ['software_id'], ['software_id'])
        batch_op.create_foreign_key(batch_op.f('fk_report_source_id_source'), 'source', ['source_id'], ['source_id'])

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_software_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_software_user_id_user'), 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_source_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_source_user_id_user'), 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_tag_software_id_software', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_source_id_source', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tag_software_id_software'), 'software', ['software_id'], ['software_id'])
        batch_op.create_foreign_key(batch_op.f('fk_tag_source_id_source'), 'source', ['source_id'], ['source_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_tag_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tag_software_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tag_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.create_foreign_key('fk_tag_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_source_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_source_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('source_id')

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_software_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_software_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('software_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_report_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_report_software_id_software'), type_='foreignkey')
        batch_op.create_foreign_key('fk_report_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_report_source_id_source', 'source', ['source_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_software_id_software'), type_='foreignkey')
        batch_op.drop_column('source_id')
        batch_op.drop_column('software_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_category_software_id_software'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_category_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key('fk_category_software_id_software', 'software', ['software_id'], ['id'])
        batch_op.create_foreign_key('fk_category_source_id_source', 'source', ['source_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
