"""update

Revision ID: f4c6cf225953
Revises: cd89ff512136
Create Date: 2020-08-22 13:05:24.830209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c6cf225953'
down_revision = 'cd89ff512136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=False))
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_category_software_id_software'), 'software', ['software_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_category_software_id_software'), type_='foreignkey')
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###
