"""update software and similar

Revision ID: fcaf08a84c61
Revises: ca6d8ef3b555
Create Date: 2020-07-15 19:23:42.367653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaf08a84c61'
down_revision = 'ca6d8ef3b555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('softwareSimilar_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_similar_softwareSimilar_id_software'), 'software', ['softwareSimilar_id'], ['id'])
        batch_op.drop_column('softwareSimilare_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('softwareSimilare_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_similar_softwareSimilar_id_software'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'software', ['softwareSimilare_id'], ['id'])
        batch_op.drop_column('softwareSimilar_id')

    # ### end Alembic commands ###
