"""similares software

Revision ID: fea1e2d059a4
Revises: 6b422fae93fc
Create Date: 2020-07-10 00:34:54.115537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea1e2d059a4'
down_revision = '6b422fae93fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('software_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_similar_software_id_software'), 'software', ['software_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_similar_software_id_software'), type_='foreignkey')
        batch_op.drop_column('software_id')

    # ### end Alembic commands ###
