"""relacionamentos software, user, source

Revision ID: ff873d80fbb1
Revises: c5f630a4e173
Create Date: 2019-11-11 00:56:07.426143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff873d80fbb1'
down_revision = 'c5f630a4e173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('userSoftware_id', sa.Integer(), nullable=True))
    op.drop_index('ix_software_title', table_name='software')
    op.create_index(op.f('ix_software_title'), 'software', ['title'], unique=True)
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.create_foreign_key(None, 'software', 'user', ['userSoftware_id'], ['id'])
    op.drop_column('software', 'user_id')
    op.add_column('source', sa.Column('userSource_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'source', 'user', ['userSource_id'], ['id'])
    op.drop_column('source', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_column('source', 'userSource_id')
    op.add_column('software', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.create_foreign_key(None, 'software', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_software_title'), table_name='software')
    op.create_index('ix_software_title', 'software', ['title'], unique=False)
    op.drop_column('software', 'userSoftware_id')
    # ### end Alembic commands ###
